language: go
os:
- linux
- osx
go:
- 1.9.x
script: make build
matrix:
  allow_failures:
  - go: tip
git:
  submodules: false
deploy:
  on:
    all_branches: true
  provider: bintray
  user: buddyspike
  key:
    secure: qrczIs3fn6gRSG62KT3X0Y0vxGF1sUzfJiGDfKH+lfkQOHmdX5prfo5+qKuHh/+SA49PNZDcHUeO5LrvqDeQZp6cTIqhzsmuV8NfHVTZSMTky1pGimONJeGnlTXz39Zokh5tbnlA6fxQ4Oiss3Ud2/XCmCSzGIukWZ9/62ZZogaHZYX8kumWGBXZMVNLnu/N+ejGvqyHUjBp/pBAg/PnqGT0dqMcDLd2KXdXqEuy+IY8gAjwdASX+v6pV8tQIzHsWmTt0MHK6MmNDMrK6KyWq6irPTJzKe4FUdJYIaXiVKrezJzue+TwP2VyMMYBjnaLQDYOtTxxOURB4C6KTGckzPawFLuG3YfK+No8ZQ4TgQLUO6tZepO5lZ0OAthpoCP4RF+rWk+wE1Na33UdBhExd2Q+/EEqcz4qFPnUqLsM0Z12tURWU2SyT8jUsB+ZBcjHDHrX0hgyIBU/H/n75WasClv1qN7vW4wxvFIJfI6I/aQLPMy/b8kttqnaF5VRdbZqGBlvl+biAutfQjrAO9q9633QhQkOUWvLK108xrZclec2BAdaenlRXTEOtlRulEmcgY8YWDGtFzpq8GAwQj6ZC3Gw0WAvJ0NCSxQy5qPz4B618FtiOAx2qiIi1JuNvKEtGR5cgoJUfH0Kt4o2WJXMSwkBF4DtrAEa2EuMmIx74A4=
  file: "./build/bintray.json"
env:
  global:
    secure: WB/4RQ8P5Q8MkGzASC6mFdEwrXVmKoeTlzzMcZh63GuoVk2vPhREvgZKc0o48+b/w3P2kv9NOfr3aFUTNt4fLKqjzAmUb3fKe2ISim727QnS4SMo7UN4Oj+/7ipQqRNR2LO3p01uIbhLVhPs/398i/ZnCjHObcX4cADOO2SwgjRYJw/92+qT80JY7DMIBfzCfKUxz/BV5qqSPMoO2IEUkIXz8oQHo1LD5Bq6Qrfxx8kRbLIFDZASG7CYPR3FOCYuXvAltzrBd0fxW8/VzHgjpjkQHxQuBt95UT3pSuA0MPOFjAUSBQ90MIsRSdqNnvuA+eykgU+QY0Twzt1u2SIJvdGHfU4FnZrwWnnkHVlMnaM/KpsbJ0pGJO078+uZb8S1qq3QMLAzJ6NJSbtZKLPLNMqrIf/Oi/NSCGE8kfU0FMMaC8R8UuGypc218LsUNnkH0vcRx7WNkiOnGd6RTvKOx14k2DnzHJBXwlmAg0PA1wY+kw31hRdIVgeuFYzjSK/0ikZJ3cMy4JREpOtSew15MkpMDAMX9SCo0/xH1H10RRqQcKMVNrMRDxzYuQa4h6GcnTu76fNw/MbWq7JN6KlcKupeK1IJpmorqj/lrywu/fZLJWQPUfkdNOJmzkplVBNVJHYPe3SF4VMLzFnz4qNasRJIk2noXp8eXWv/hOFEzQ8=
