language: go
os:
- linux
- osx
go:
- 1.9
script: make build
matrix:
  allow_failures:
  - go: tip
git:
  submodules: false
branches:
  only:
  - master
  - release
deploy:
  on: release
  provider: bintray
  user: buddyspike
  key:
    secure: jihy8muom6pVkbAmOJfbvfoNlVQ6xDEctux0Vc8TCj9LsPA3Glzh8VFm5IFMKVErh3GbuOy93+gbxO+asKQ5Ftr0Yet9DlGrsSUovcLejvpeVvgnXnqffeWcSVJkY0UN02oh7r0yG0c6on2++qpZYtZPjv/dOheu3daKstKY7O6WABMQ50vCGOo0brtmLRXgsupE5A8lBDIZRVw+T4b2Wi/GPZt4GgfjACpxHDL1r1RzmtafEtsaC+YBT9+zKHEfJPw1BFpC+kFgWPdGLWLRhhIbAfGVs8G3YzT+ujTpx4pPdZk/SUTmvX3kipLtr8rtIsA52pTUdM8lwGrHl0nkK/OCHk3AoDA91YMWgEHsTtaC6EJmTlQCaS/PF4iHXqBd5Hzm4Ez1CFhZYOd2e+Yuv/1G/OUelgHUTaABMR8xrYIhQ3sYkT7vde9G71BH6kEGz+6D7JhghhXhxDRKO4cyad1nWgNnwpNDxeBn3avdUZdi3c2zP9ELeTjnLFGnZRDzsGtjDfSWHXjTHetYt1KFbNMDfaz1kmIH69oONVhiCSsM2nl+57oRcwPEV8EoODONCrui6X2Pj7Sn1SWH9Ec95Aj1HCMOlAWuLH1dlsaEf60dkQ7Ebh1fU589j+0sB/Fgou8ttJYMPDxHmxvJK85Ta5GqWF3juBOBQLPDqfkrkVk=
  file: "./build/bintray.json"
env:
  global:
    secure: AJ4DACXQEc4BabPAF3yLmfTsX+3MmhWoQRdD/9FhtruEvYBMbylGVX1WqofJj3B96BARlK4OUifML1YjgUNGcvpIDAlTh0IZOb3KAWLpN7sFjRkf32NexRwTAcCrMlMz8z+5gBGoP2XcN7rTodeASTz7Q9IjQoAQx6x6CTkx7fp6SVMHquflXKMMHnJ9RuMnsDFIW9bYhSTa1kUVrrUIOCXbLX9139AjxvOaG4B/dw8mtZT3xGMOA6ZOCajIZBHOrMGDBDiPvjoT99m5Iz5EyO0rS7W8x71VlmLaAFCduUqTEroww0MU/6UTelpUJjJfniQJZB2A/Id826UKjeW0Afr22My/vKerqk7b1By/b/QwipgY4Ck6sFlHvdcMqzogvARKOk+k079LgelP38nK1nPEMz8GPX2pQNyvwTWM1IgQ4z23VlIvXjYPbRNaojn6NDz8Jq0hdi8E0rEY3AOskFQbA7u635ZLemmIRdAmCNLJ7CiKxoZFK/pcq15+N2IqYFRychqvpaJ6m8mBOUHS9j8RI2SJxsWfZZiHUBV68Q480G7+UNd4bQuweVKuzZ1jHskuSTEX9/jNw3G1YPv+PuPfGS25HtRuNSIZgILd82u56B+fVC8gt5UHhH+0PUdiZduFYUJizpYPAJUdng7ATz5SJ8IZyZ8/Y5t8KJOsYrE=
