language: go

go:
  - 1.9
  - tip

script: make build

matrix:
  allow_failures:
    - go: tip

git:
  submodules: false

branches:
  only:
  - master

addons:
  apt:
    packages:
    - cmake
    - libssh2-1-dev
    - openssh-client
    - openssh-server
    - valgrind
    - libssl-dev
    - openssl

