language: go

go:
  - 1.9
  - tip

script: make build

matrix:
  allow_failures:
    - go: tip

git:
  submodules: false

branches:
  only:
  - master

before_install:
    sudo apt-get install libssh2-1-dev -y

