language: go
os:
- linux
- osx
go:
- 1.9
script: make build
matrix:
  allow_failures:
  - go: tip
git:
  submodules: false
branches:
  only:
  - master
  - release
deploy:
  on: release
  provider: bintray
  user: buddyspike
  key:
    secure: jihy8muom6pVkbAmOJfbvfoNlVQ6xDEctux0Vc8TCj9LsPA3Glzh8VFm5IFMKVErh3GbuOy93+gbxO+asKQ5Ftr0Yet9DlGrsSUovcLejvpeVvgnXnqffeWcSVJkY0UN02oh7r0yG0c6on2++qpZYtZPjv/dOheu3daKstKY7O6WABMQ50vCGOo0brtmLRXgsupE5A8lBDIZRVw+T4b2Wi/GPZt4GgfjACpxHDL1r1RzmtafEtsaC+YBT9+zKHEfJPw1BFpC+kFgWPdGLWLRhhIbAfGVs8G3YzT+ujTpx4pPdZk/SUTmvX3kipLtr8rtIsA52pTUdM8lwGrHl0nkK/OCHk3AoDA91YMWgEHsTtaC6EJmTlQCaS/PF4iHXqBd5Hzm4Ez1CFhZYOd2e+Yuv/1G/OUelgHUTaABMR8xrYIhQ3sYkT7vde9G71BH6kEGz+6D7JhghhXhxDRKO4cyad1nWgNnwpNDxeBn3avdUZdi3c2zP9ELeTjnLFGnZRDzsGtjDfSWHXjTHetYt1KFbNMDfaz1kmIH69oONVhiCSsM2nl+57oRcwPEV8EoODONCrui6X2Pj7Sn1SWH9Ec95Aj1HCMOlAWuLH1dlsaEf60dkQ7Ebh1fU589j+0sB/Fgou8ttJYMPDxHmxvJK85Ta5GqWF3juBOBQLPDqfkrkVk=
  file: "./build/bintray.json"
env:
  global:
    secure: Ek5EpfkkdIsmzsK3m7cBujQRPa8tHd4wArfHoSNJv6uES+p0RTX5EosjNaa+1przbB6jTF5d9Q5gFOWS1susCg/mYj3ChG8IferypPT4hACqEMxo0vROuOLcGMwlK3ya2v35DpCKBqYbhLV1RjKU8vZTcu59yn4s6fNfnCWr3BNhLJABsFblhTPLzzmBxXgI95iP5qtpTv3Sxu/+7MlrBHfdg3qeishovkQ9uhLiQ1io2YAQkQOYqdgr4mWxgjeULp+M/kmf4Rwb0TVW322zD+Gu9OjqEAFQWwRh9XDF0fOOrYJzp0WDDomSJ32VPtqspXzrp8dWfIguibrDcJz7dkB9EonbU366y40CS8rZhmMRmWDWFUPcTrZ4rxmOtw/qOL4zalO2XTgTf86zRG5VC2XbM0a/ibMLfVbSrY179vTEn9eScGXeP/OWfy3aFLgg+rTLDfHz63/HAeo+j5s6B8xxlgTrFiN5LQaBgA9WSC0LD5jf5mtWQqBBgB9n6DFNLS+igkeAaXns/EW9VP8YjJF3bT/LY4E+mZOqKsfawXs+ug+ptbIwmej+4k0Q3U7wgX67pDaF33BBUuJHKd1xG1SD2rFZ0wA3SJUU6JsbvKKLHA4Bvz/j6oU/r9DflkJxEwbQc2+Eb516n74l8H0rh0t4jjiUpXBLvWLaddflB7Y=
